spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ACADEMY_USER?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: Catkik999129#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update